### ISSUE TITLE
Set up reasonable development cycle

### ISSUE THREAD

**Issue by petrpajdla** [ARUP-CAS/aiscr-webamcr-help#2]
### TODO:

- [x] Protect main branch
- [x] Create dev branch
- [x] Build site only after merge from dev -> main branch
